language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
python:
  - "3.7"
install:
  - pip install -r requirements_dev.txt
env:
  global:
    - DJANGO_SETTINGS_MODULE=siice.settings.testing
script:
  - coverage run --rcfile=.coveragerc manage.py test -v 2
after_success:
  - codecov
