# Generated by Django 3.0.2 on 2020-04-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='document_year',
            new_name='year',
        ),
    ]
