# Generated by Django 3.0.2 on 2020-05-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_secondment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dependency',
        ),
        migrations.RemoveField(
            model_name='application',
            name='secondment',
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.Position'),
        ),
    ]
