# Generated by Django 3.0.2 on 2020-04-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200407_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='polygraphic',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='psychological',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='socioeconomic',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='toxicological',
            name='alert',
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
                ('section', models.CharField(choices=[('socioeconomic', 'socioeconomic'), ('medical', 'medical'), ('polygraphic', 'polygraphic'), ('psychological', 'psychological'), ('toxicological', 'toxicological')], max_length=64)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.Evaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
