# Generated by Django 3.0.2 on 2020-05-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200509_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='resources',
            field=models.CharField(choices=[('fortaseg', 'fortaseg'), ('fasp', 'fasp'), ('other', 'other')], default='fortaseg', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='schema',
            field=models.CharField(choices=[('integral', 'integral'), ('differentiated', 'differentiated'), ('filter', 'filter')], default='integral', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('ise_auth_pending', 'ise_auth_pending'), ('schedule_pending', 'schedule_pending'), ('schedule_pending', 'schedule_pending')], default='created', max_length=255),
        ),
        migrations.AddField(
            model_name='medical',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polygraphic',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychological',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socioeconomic',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toxicological',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
