# Generated by Django 3.0.2 on 2020-04-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200409_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='alerted_at',
        ),
        migrations.RemoveField(
            model_name='polygraphic',
            name='alerted_at',
        ),
        migrations.RemoveField(
            model_name='psychological',
            name='alerted_at',
        ),
        migrations.RemoveField(
            model_name='socioeconomic',
            name='alerted_at',
        ),
        migrations.RemoveField(
            model_name='toxicological',
            name='alerted_at',
        ),
    ]
