# Generated by Django 3.0.2 on 2020-04-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_schemas', '0001_initial'),
        ('api', '0006_auto_20200409_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='eval_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_eval', to='drf_schemas.Item'),
        ),
        migrations.AddField(
            model_name='polygraphic',
            name='eval_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygraphic_eval', to='drf_schemas.Item'),
        ),
        migrations.AddField(
            model_name='psychological',
            name='eval_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychological_eval', to='drf_schemas.Item'),
        ),
        migrations.AddField(
            model_name='socioeconomic',
            name='eval_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socioeconomic_eval', to='drf_schemas.Item'),
        ),
        migrations.AddField(
            model_name='toxicological',
            name='eval_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toxicological_eval', to='drf_schemas.Item'),
        ),
    ]
